<?php

use Illuminate\Database\Seeder;

class UserDetailTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_detail')->delete();
        
        \DB::table('user_detail')->insert(array (
            0 => 
            array (
                'id' => 1,
                'uid' => 1,
                'realname' => NULL,
                'realname_status' => 0,
                'sex' => 0,
                'mobile' => NULL,
                'mobile_status' => 0,
                'nickname' => NULL,
                'qq' => NULL,
                'qq_status' => 0,
                'wechat' => NULL,
                'wechat_status' => 0,
                'card_number' => NULL,
                'province' => NULL,
                'city' => NULL,
                'area' => NULL,
                'avatar' => 'attachment/user/2016/08/03/9a2d12cf0cd2c1f143440c32ff713726.png',
                'autograph' => NULL,
                'introduce' => NULL,
                'sign' => NULL,
                'employee_praise_rate' => NULL,
                'employer_praise_rate' => NULL,
                'receive_task_num' => NULL,
                'publish_task_num' => NULL,
                'shop_status' => 1,
                'balance' => '965694.00',
                'balance_status' => 0,
                'last_login_time' => '2016-08-03 15:35:15',
                'backgroundurl' => NULL,
                'alternate_tips' => 1,
                'created_at' => '2016-08-03 15:35:15',
                'updated_at' => '2016-08-03 17:06:10',
            ),
            1 => 
            array (
                'id' => 2,
                'uid' => 2,
                'realname' => NULL,
                'realname_status' => 0,
                'sex' => 0,
                'mobile' => NULL,
                'mobile_status' => 0,
                'nickname' => NULL,
                'qq' => NULL,
                'qq_status' => 0,
                'wechat' => NULL,
                'wechat_status' => 0,
                'card_number' => NULL,
                'province' => NULL,
                'city' => NULL,
                'area' => NULL,
                'avatar' => NULL,
                'autograph' => NULL,
                'introduce' => NULL,
                'sign' => NULL,
                'employee_praise_rate' => NULL,
                'employer_praise_rate' => NULL,
                'receive_task_num' => NULL,
                'publish_task_num' => NULL,
                'shop_status' => 1,
                'balance' => '995337.00',
                'balance_status' => 0,
                'last_login_time' => '2016-08-03 15:41:33',
                'backgroundurl' => NULL,
                'alternate_tips' => 1,
                'created_at' => '2016-08-03 15:41:33',
                'updated_at' => '2016-08-03 16:59:10',
            ),
            2 => 
            array (
                'id' => 3,
                'uid' => 3,
                'realname' => NULL,
                'realname_status' => 0,
                'sex' => 0,
                'mobile' => NULL,
                'mobile_status' => 0,
                'nickname' => NULL,
                'qq' => NULL,
                'qq_status' => 0,
                'wechat' => NULL,
                'wechat_status' => 0,
                'card_number' => NULL,
                'province' => NULL,
                'city' => NULL,
                'area' => NULL,
                'avatar' => NULL,
                'autograph' => NULL,
                'introduce' => NULL,
                'sign' => NULL,
                'employee_praise_rate' => NULL,
                'employer_praise_rate' => NULL,
                'receive_task_num' => NULL,
                'publish_task_num' => NULL,
                'shop_status' => 0,
                'balance' => '995499.00',
                'balance_status' => 0,
                'last_login_time' => '2016-08-03 15:44:30',
                'backgroundurl' => NULL,
                'alternate_tips' => 0,
                'created_at' => '2016-08-03 15:44:30',
                'updated_at' => '2016-08-03 17:34:07',
            ),
            3 => 
            array (
                'id' => 4,
                'uid' => 4,
                'realname' => NULL,
                'realname_status' => 0,
                'sex' => 0,
                'mobile' => NULL,
                'mobile_status' => 0,
                'nickname' => NULL,
                'qq' => NULL,
                'qq_status' => 0,
                'wechat' => NULL,
                'wechat_status' => 0,
                'card_number' => NULL,
                'province' => NULL,
                'city' => NULL,
                'area' => NULL,
                'avatar' => 'attachment/user/2016/08/03/541f696f0d340ddb29ccfedf15e0e815.jpg',
                'autograph' => NULL,
                'introduce' => NULL,
                'sign' => NULL,
                'employee_praise_rate' => NULL,
                'employer_praise_rate' => NULL,
                'receive_task_num' => NULL,
                'publish_task_num' => NULL,
                'shop_status' => 0,
                'balance' => '999999.00',
                'balance_status' => 0,
                'last_login_time' => '2016-08-03 15:54:37',
                'backgroundurl' => NULL,
                'alternate_tips' => 1,
                'created_at' => '2016-08-03 15:54:37',
                'updated_at' => '2016-08-03 16:53:05',
            ),
            4 => 
            array (
                'id' => 5,
                'uid' => 5,
                'realname' => NULL,
                'realname_status' => 0,
                'sex' => 0,
                'mobile' => NULL,
                'mobile_status' => 0,
                'nickname' => NULL,
                'qq' => NULL,
                'qq_status' => 0,
                'wechat' => NULL,
                'wechat_status' => 0,
                'card_number' => NULL,
                'province' => NULL,
                'city' => NULL,
                'area' => NULL,
                'avatar' => 'attachment/user/2016/08/03/105566b304e120ab54eca79e401f7ded.gif',
                'autograph' => NULL,
                'introduce' => NULL,
                'sign' => NULL,
                'employee_praise_rate' => NULL,
                'employer_praise_rate' => NULL,
                'receive_task_num' => NULL,
                'publish_task_num' => NULL,
                'shop_status' => 1,
                'balance' => '50000.00',
                'balance_status' => 0,
                'last_login_time' => '2016-08-03 16:11:01',
                'backgroundurl' => NULL,
                'alternate_tips' => 1,
                'created_at' => '2016-08-03 16:11:01',
                'updated_at' => '2016-08-03 17:12:30',
            ),
            5 => 
            array (
                'id' => 6,
                'uid' => 6,
                'realname' => NULL,
                'realname_status' => 0,
                'sex' => 0,
                'mobile' => NULL,
                'mobile_status' => 0,
                'nickname' => NULL,
                'qq' => NULL,
                'qq_status' => 0,
                'wechat' => NULL,
                'wechat_status' => 0,
                'card_number' => NULL,
                'province' => NULL,
                'city' => NULL,
                'area' => NULL,
                'avatar' => NULL,
                'autograph' => NULL,
                'introduce' => NULL,
                'sign' => NULL,
                'employee_praise_rate' => NULL,
                'employer_praise_rate' => NULL,
                'receive_task_num' => NULL,
                'publish_task_num' => NULL,
                'shop_status' => 0,
                'balance' => '0.00',
                'balance_status' => 0,
                'last_login_time' => '2016-08-03 18:24:48',
                'backgroundurl' => NULL,
                'alternate_tips' => 0,
                'created_at' => '2016-08-03 18:24:48',
                'updated_at' => '2016-08-03 18:24:48',
            ),
        ));
        
        
    }
}
